### ISSUE TITLE
Dependency on @vue/composition-api should be removed when used with vue2.7 

### ISSUE THREAD

**Issue by altryne** [storyblok/storyblok-vue-2#83]
I'm currently playing around with upgrading to vue 2.7 Naruto, and per the documentation, all it includes compositionApi. 

`
⚠️ With the release of [Vue 2.7](https://blog.vuejs.org/posts/vue-2-7-naruto.html), which has Composition API built-in, you no longer need this plugin. Thereby this plugin has entered maintenance mode and will only support Vue 2.6 or earlier. This project will reach End of Life by the end of 2022.
`

**Comment by Dawntraoz** [comment]
This was resolved in v2.0.0 version of this package -> https://github.com/storyblok/storyblok-vue-2/releases/tag/v2.0.0
